{% set name = "sdeconv" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/sylvainprigent/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 81998622f08f3cddd5a81785ab9b1bfaee848ac0250d5d35f2edbcdd5fa1e939

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - fftw
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - python
    - pip
    - numpy
    - scipy
    - setuptools
  run:
    - joblib
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - threadpoolctl

test:
  imports:
    - sdeconv
    - sdeconv.deconv
  requires:
    - pip
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/sylvainprigent/sdeconv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python library for 2D and 3D image deconvolution'

extra:
  recipe-maintainers:
    - goanpeca
    - sylvainprigent
