{% set name = "sdeconv" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sylvainprigent/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8a3fb0706eee7b942a6704532c3cd7ae698d5acd89d6a5585d018d1341bbfbd0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython
    - fftw
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - python
    - pip
    - numpy
    - scipy
    - setuptools
  run:
    - joblib
    - {{ pin_compatible('numpy') }}
    - python
    - pytorch
    - scikit-image
    - scipy
    - threadpoolctl
    - torchvision

test:
  imports:
    - sdeconv
    - sdeconv.deconv
  requires:
    - pip
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/sylvainprigent/sdeconv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for 2D and 3D image deconvolution

extra:
  recipe-maintainers:
    - goanpeca
    - sylvainprigent
